name: Deploy Web

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Clear cache
      run: |
        chmod +x ./.github/scripts/clear-cache.sh
        ./.github/scripts/clear-cache.sh

    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build:web
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        enable_jekyll: false
        keep_files: false 